//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.RightNow.Cti.MediaBar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oracle.RightNow.Cti.MediaBar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.answer.png.
        /// </summary>
        internal static string AnswerImageUri {
            get {
                return ResourceManager.GetString("AnswerImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string AnswerTooltip {
            get {
                return ResourceManager.GetString("AnswerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.hangup.png.
        /// </summary>
        internal static string HangupImageUri {
            get {
                return ResourceManager.GetString("HangupImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang up.
        /// </summary>
        internal static string HangupTooltip {
            get {
                return ResourceManager.GetString("HangupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.hold.png.
        /// </summary>
        internal static string HoldImageUri {
            get {
                return ResourceManager.GetString("HoldImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the interaction on hold.
        /// </summary>
        internal static string HoldTooltip {
            get {
                return ResourceManager.GetString("HoldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string InteractionStateActive {
            get {
                return ResourceManager.GetString("InteractionStateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialing.
        /// </summary>
        internal static string InteractionStateDialing {
            get {
                return ResourceManager.GetString("InteractionStateDialing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string InteractionStateDisconnected {
            get {
                return ResourceManager.GetString("InteractionStateDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        internal static string InteractionStateHeld {
            get {
                return ResourceManager.GetString("InteractionStateHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing.
        /// </summary>
        internal static string InteractionStateRinging {
            get {
                return ResourceManager.GetString("InteractionStateRinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string MediaTypeChat {
            get {
                return ResourceManager.GetString("MediaTypeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string MediaTypeEmail {
            get {
                return ResourceManager.GetString("MediaTypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.email.png.
        /// </summary>
        internal static string MediaTypeEmailImageUri {
            get {
                return ResourceManager.GetString("MediaTypeEmailImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MediaTypeUnknown {
            get {
                return ResourceManager.GetString("MediaTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string MediaTypeVoice {
            get {
                return ResourceManager.GetString("MediaTypeVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.voice.png.
        /// </summary>
        internal static string MediaTypeVoiceImageUri {
            get {
                return ResourceManager.GetString("MediaTypeVoiceImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web incident.
        /// </summary>
        internal static string MediaTypeWeb {
            get {
                return ResourceManager.GetString("MediaTypeWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.web.png.
        /// </summary>
        internal static string MediaTypeWebImageUri {
            get {
                return ResourceManager.GetString("MediaTypeWebImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no active interaction.
        /// </summary>
        internal static string NoInteractionTimer {
            get {
                return ResourceManager.GetString("NoInteractionTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.retrieve.png.
        /// </summary>
        internal static string RetrieveImageUri {
            get {
                return ResourceManager.GetString("RetrieveImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the interation.
        /// </summary>
        internal static string RetriveTooltip {
            get {
                return ResourceManager.GetString("RetriveTooltip", resourceCulture);
            }
        }
    }
}
